version: "3"

services:
  garden:
    hostname: "garden"
    container_name: "garden"
    build: "."
    ports:
      - "4000:4000"
    # Uncomment this to see changes live
    volumes:
      - "./:/site"
      # - "./_notes-test:/site/_notes"
      - "garden_exclude_site:/site/_site"
      - "garden_exclude_cache:/site/.jekyll-cache"
    restart: "no"

volumes:
  garden_exclude_site:
  garden_exclude_cache:
